ibm-openbmc/phosphor-led-manager

configs/ibm,everest/led-group-config.json

everest LED: Changes in the everest group json to accomodate
1) Power supply naming changes
2) Add lcd panel along with existing base panel
3) Some name updates to change from pca955x_ to lcd_
4) Add cablecard_01 top and bottom fault and identify LEDs
Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
Change-Id: I9615aa6fb93cf5c5928d8b31a6c5189eaeefa4cc

everest LED: Changes in the everest group json new inventory changes

---

configs/ibm,rainier-4u/led-group-config.json

Fix the LED json where the name for PCIe Slot9 identify
LED has been wrongly specified.
Signed-off-by: Jinu Joy Thomas <jinu.joy.thomas@in.ibm.com>

Fix PCIe Slot9 Identify LED name

---

configs/ibm,everest/led-group-config.json
configs/ibm,rainier-1s4u/led-group-config.json
configs/ibm,rainier-2u/led-group-config.json
configs/ibm,rainier-4u/led-group-config.json

Add enclosure identify rollup for Loction codes which do
not have physical LED.
Also corrected certain name errors in the json file.
Signed-off-by: Jinu Joy Thomas <jinu.joy.thomas@in.ibm.com>

Added Miscellaneous FRU identify rollup

---

configs/ibm,rainier-1s4u/led-group-config.json

The led group associations for dimms was pointing to incorrect
dimm inventory paths in rainier 1s4u led config json.
This commit has the correction in all the dimm association entries.
Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>

DIMM association correction in 1S4U config json

---

fault-monitor/operational-status-monitor.cpp
fault-monitor/operational-status-monitor.hpp
utils.hpp

When a faulty CEC FRU is repaired or replaced during runtime,
its corresponding chassis critical associations were left unremoved.
This leads in displaying Chassis Health Rollup as "Critical" in GUI even
after the fault FRU is repaired/replaced.
This commit has changes that removes the critical association on chassis,
when the FRU's "Functional" property (present under the d-bus interface
"xyz.openbmc_project.State.Decorator.OperationalStatus") is changed from
false to true, which indicates that the FRU is repaired and is functional.
This is needed to handle hotpluggable or concurrently maintainable FRUs
which are associated with the chassis.
Test:
busctl get-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/dcm0/cpu0 …

Remove critical associations for a repaired CEC FRU.

---

group.cpp
group.hpp
lamptest.cpp
lamptest.hpp

This patch solves two issues in lamp test
1. Reset lamp test timer on assert to assert case
2. Reject stopping lamp test when there is a request to
deassert lamp test.
Tested by adding print statements. Needs testing from lab.
Tested from GUI as well. Code works as expected.
================================
Test case 1:
Start lamp test . Curr state = false; Set it to true.
Result: 4mins of lamp test execution + Asserted should be back to false after 4mins
OUTPUT:
Aug 01 14:12:25 p10bmc phosphor-ledmanager[506]: Lamptest starts
Aug 01 14:12:25 p10bmc pldmd[1633]: Lamp Test: The state set PDR can not be found, entityType = 32787
Aug 01 14:12:25 p10bmc phosphor-ledmanager[506]: Failed to set Asserted property, ERROR = sd_bus_call noreply: org.freedesktop.DBus.Error.InvalidArgs: Invalid …

Lamp test issues resolved

---

configs/ibm,rainier-4u/led-group-config.json

Removed the unused group 'connector10_identify' for Rainier 4U system. Removed the unused group 'connector16_identify' for Rainier 4U system.
Signed-off-by: Kantesh Nagaradder <kantesh.nagaradder@ibm.com>

BMC:LED:Removed the unused LED groups from LED config JSON file for Rainier 4U system

---

lamptest.cpp
led-main.cpp
meson.build

In case lamp test has been trigerred and reboot takes place, even after reboot the lamps are found to be in the on state.
The commit switches off the lamps in case such situation is found and restores the LEDs to the state in which they were before lamp test was trigerred.
The change was done against "PE00DKX2".

Reset lamps after reboot

---

group.hpp

`sdbusplus::server::object_t` has long had an enum-based parameter for signal action, but maintained a backwards compatible boolean mapping. It is time to remove this boolean to make it more observable which actions are being used in applications.  Map all `true` occurrences to `action::defer_emit`.
Change-Id: I5fc79b0851bd5901b5b6c8dd24a291825163dbad

sdbusplus: object: don't use 'bool' argument constructor

---

lamptest.cpp
meson.build

When there is a request to stop lamp test, the below trace
"Lamp test is still running. Cannot force stop the lamp test.
Asserted is set back to true."
is getting printed even if the lamp test is not actually started.
This commit handles printing the above mentioned trace only when the lamp test timer got started and not expired.
Test:
busctl set-property xyz.openbmc_project.LED.GroupManager /xyz/openbmc_project/led/groups/lamp_test xyz.openbmc_project.Led.Group Asserted b false
In journal no traces are seen with respect to lamp test.

Lamp test: Handle false trace getting printed

---

fault-monitor/operational-status-monitor.cpp

The LED fault association group name has been changed from fault_led_group to fault_identifying. The code points to the invalid group name. This commit has the fix for it.
Test:
busctl set-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/vdd_vrm1 xyz.openbmc_project.State.Decorator.OperationalStatus Functional b false
busctl set-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/ebmc_card_bmc xyz.openbmc_project.State.Decorator.OperationalStatus Functional b true
Before the fix: Error traces are found when we try to set Functional property.
phosphor-fru-fault-monitor[1180]: Failed to get endpoints property, ERROR = sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: …

LED:Invalid association for fault LED group

---

meson.build
scripts/oem/set-guarded-fru-leds.sh

The script checks for guarded FRUs and sets the operational status as false for those FRUs.
The script does not operate in chassis on condition.

Set operational status for guarded FRUs

---

manager/json-config.hpp
manager/json-parser.hpp
manager/led-main.cpp
meson.build
subprojects/CLI11.wrap

To facilitate localized testing of JSON config loading, add an option that allows the configuration to be directly passed, rather than try to determine it from entity-manager config off dbus.
Change-Id: I80d7051bf312044c68f44bcdb9ac02364f9abac3

led-manager: add CLI11 option and config loading

---

fault-monitor/fru-fault-monitor.cpp
fault-monitor/operational-status-monitor.cpp
manager/json-config.hpp
manager/json-parser.hpp
manager/ledlayout.hpp
manager/manager.hpp
scripts/parse_led.py
test/led-test-map.hpp
utils.cpp
utils.hpp

Generally, unordered_maps should be preferred over map because they have faster access times (O(1)) and tend to allocate less dynamic memory.  We do not rely on ordered iteration in any current use of maps, so it is safe to do a full replace.
Change-Id: Ieaa28ac7f70f9913d13d25142fea9861d49bb23f

switch map to unordered_map

---

manager/led-main.cpp
manager/manager.cpp
manager/manager.hpp

The current manager performs LED ActionSet one-time only when LED group asserted property changes, so if the physical LED object path is not ready when it is set, the LED will be in an error state. Most of time this error occurs at BMC booting due phospohr-led-manager starts before LED driver is probed.
In order to correct LED state after physical LED is ready, add a timer to repeatedly setting failed LED after 1 second.
Test:
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging
xyz.openbmc_project.Logging.Create Create ssa{ss}
xyz.openbmc_project.Power.PowerSupply.Error.Fault
xyz.openbmc_project.Logging.Entry.Level.Error 1 CALLOUT_INVENTORY_PATH /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0
reboot
cat /sys/class/leds/cffps2-68/brightness
255
cat …

1060:manager: add timer for failed LED actions

---

fault-monitor/fru-fault-monitor.cpp
fault-monitor/fru-fault-monitor.hpp
fault-monitor/monitor-main.cpp
fault-monitor/operational-status-monitor.cpp
fault-monitor/operational-status-monitor.hpp
manager/group.hpp
manager/json-config.hpp
manager/lamptest/lamptest.cpp
manager/led-main.cpp
manager/manager.cpp
manager/manager.hpp
manager/serialize.hpp
meson.build
pyproject.toml
subprojects/cereal.wrap
test/utest.cpp
utils.cpp
utils.hpp

Pulled  below commits from upstream.
- 1f0b715 Use the lower camel case of the C++ standard.
- 785f505 lamp test: Fix calling GetSubTreePaths method
- b4c82cf support sdbusplus::message::object_path.
- 3e073ba sdbusplus: use shorter type aliases
- fccfac9 parse_led: format with black
- d1c1f0e meson: add proper cereal dependency
- c5e0f31 Fix some warnings by cppcheck
Tested Patch on HW physically .

Led upstream commits

---

manager/group.cpp
manager/json-parser.hpp
manager/lamptest/lamptest.cpp
manager/lamptest/lamptest.hpp
manager/led-main.cpp
manager/ledlayout.hpp
manager/manager.cpp
manager/manager.hpp
scripts/parse_led.py
test/led-test-map.hpp
test/utest-led-json.cpp
test/utest.cpp

Rather than scattered map and set typedefs, centralize the two common structures into 'ledlayout.hpp': ActionSet, GroupMap.  Use them everywhere where previous raw maps and sets were used.
Test:
Toggled identify leds in GUI and checked on System, reflecting the impact fine-
cat /var/lib/phosphor-led-manager/savedGroups 
{
"value0": [
"/xyz/openbmc_project/led/groups/bmc_booted",
"/xyz/openbmc_project/led/groups/cpu0_identify",
"/xyz/openbmc_project/led/groups/enclosure_identify"
]
}
cat /sys/class/leds/pca955x:cpu0/brightness 
255
cat /sys/class/leds/rear-enc-id0/brightness                       
1
Change-Id: I0ed5203146a6486a49caf4000f545ded0088dc15

Upstream sync: use common types everywhere

---

led-main.cpp
manager.cpp
manager.hpp

The current manager performs LED ActionSet one-time only when LED group asserted property changes, so if the physical LED object path is not ready when it is set, the LED will be in an error state. Most of time this error occurs at BMC booting due phospohr-led-manager starts before LED driver is probed.
In order to correct LED state after physical LED is ready, add a timer to repeatedly setting failed LED after 1 second.
Test works as expected:
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging xyz.openbmc_project.Logging.Create Create ssa{ss}  xyz.openbmc_project.Power.PowerSupply.Error.Fault xyz.openbmc_project.Logging.Entry.Level.Error 1 CALLOUT_INVENTORY_PATH /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0
reboot
cat …

1050:manager: add timer for failed LED actions

---

led-main.cpp
manager.cpp
manager.hpp

The current manager performs LED ActionSet one-time only when LED group asserted property changes, so if the physical LED object path is not ready when it is set, the LED will be in an error state. Most of time this error occurs at BMC booting due phospohr-led-manager starts before LED driver is probed.
In order to correct LED state after physical LED is ready, add a timer to repeatedly setting failed LED after 1 second.
Test:
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging
xyz.openbmc_project.Logging.Create Create ssa{ss}
xyz.openbmc_project.Power.PowerSupply.Error.Fault
xyz.openbmc_project.Logging.Entry.Level.Error 1 CALLOUT_INVENTORY_PATH /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0
reboot
cat /sys/class/leds/cffps2-68/brightness
255
cat …

1020:manager: add timer for failed LED actions

---

meson.build

Meson 1.1.1 and GCC-13 both support C++23 and a sufficient portion of the standard has been implemented.  Upgrade the build to leverage it.
Change-Id: Ie0245d2667cfb2917e1af6d57f82a1d20fef8d60

build: upgrade to C++23

---

meson.build
subprojects/CLI11.wrap
subprojects/phosphor-dbus-interfaces.wrap
subprojects/phosphor-logging.wrap
subprojects/sdeventplus.wrap

Leverage wrapfile `[provide]` directives to simplify the dependency searching in the meson.build.
Change-Id: I4b8aac501a91075b092552daf6735037f6968d7e

meson: simplify dependencies

---

meson_options.txt

In order to get broader testing in CI, enable use-json by default. This is the preferred system configuration direction.
Change-Id: Ice51af8a61443f30e42741fdd90f935cd0aa8cbf

meson: set use-json as default

---

gen/README
gen/meson.build

WARNING: Generated meson files from wrong version of sdbus++-gen-meson.
WARNING: Expected "sdbus++-gen-meson version 1",
got: sdbus++-gen-meson version 3
Add the regenerate-meson file to automatically update meson.build.
Change-Id: If1ce533bc0f6bafbe75d05595f9d36f5f652bd45

Fix sdbus++-gen-meson version warning

---

meson.options
meson_options.txt

Support has been added for reading options from meson.options instead of meson_options.txt[1]. These are equivalent, but not using the .txt extension for a build file has a few advantages, chief among them many tools and text editors expect a file with the .txt extension to be plain text files, not build scripts.
[1] https://mesonbuild.com/Release-notes-for-1-1-0.html#support-for-reading-options-from-mesonoptions
Change-Id: Icf7286351b49c526d02327e3a2d72c40b5f9a960

meson_options.txt: Support for reading options from meson.options

---

configs/config_map.json
configs/ibm,fuji/led-group-config.json

P11 Fuji is the successor of P10 Everest 4S4U system. Since there are no major differences w.r.t LED configurations, created a copy of Everest LED config JSON for Fuji system.
Change-Id: I9c400de2dca5a58b6bf866d4605f80d2e4403ddc

P11:Fuji LED Config JSON

---

meson.build
tools/main.cpp
tools/meson.build
tools/toggle-fault-leds.hpp
tools/utility.hpp

The commit implements base framework for led tool with an option to toggle fault LEDs based on the functional status of the FRU.
The tool will be auto triggered with different optiosn on BMC boot and system power on, driven via system-d service files.
Tool can be used via command line as well.

led tool: toggle fault LEDs

---

tools/main.cpp
tools/set-guarded-fru-leds.hpp

The commit implements an option to set LEDs state for FRUs which are marked as guarded.
This is required as all fault LEDs associated with FRUs gets cleared on a BMC reboot at chassis off state. To avoid losing LEDs which were lit up due to guard records, this will be excuted via service file.

Set LEDs state for guarded FRUs

---

manager/json-config.hpp

Switching led-manager to use xyz.openbmc_project.Inventory.Decorator. Compatible interface from using xyz.openbmc_project.Configuration. IBMCompatibleSystem interface.
Test:
Tested for right config json is picked based on the Names property from xyz.openbmc_project.Inventory.Decorator.Compatible interface.
./phosphor-ledmanager
Inside getFilePath
Get the NAME based json
"/usr/share/phosphor-led-manager/com.ibm.Hardware.Chassis.Model.Rainier4U.json" is selected for config file
where,
busctl Get on "xyz.openbmc_project.Inventory.Decorator.Compatible"  "Names" results as-
v as 2 "com.ibm.Hardware.Chassis.Model.Rainier4U" "com.ibm.Hardware.Chassis.Model.Rainier"
Change-Id: I48ee37cb3f11fd6cd99e913caee4ebeb2e1004c3

leds:Make use of Decorator.Compatible interface

---

tools/service/obmc-clear-all-fault-leds-and-remove-crit-association@.service

Currently the support for exe is not availlable in the build. Removing it till the support is made available.

Rmove triggerring of critical association

---

tools/main.cpp
tools/meson.build
tools/service/obmc-set-leds-default-state@.service
tools/set-leds-default-state.hpp

The commit adds option in the tool to set all the LEDs to their default state.
The service file has been added to trigger the same at every boot via recipe files.

Tool option to set LED default state

---

tools/clear-psu-fault-leds.hpp
tools/main.cpp
tools/meson.build
tools/service/obmc-clear-psu-fault-leds@.service
tools/utility.hpp

The commit provides an option to clear fault LEDs for PSU. It will also be triggered via service file on every BMC reboot.
The functionality is required as PSU handles its own fault LEDs and hence before PSU comes up any previous fault, logged in previous boot should be cleared.

CLear PSU fault LEDs

---

configs/com.ibm.Hardware.Chassis.Model.BlueRidge1S4U.json
configs/com.ibm.Hardware.Chassis.Model.BlueRidge2U.json
configs/com.ibm.Hardware.Chassis.Model.BlueRidge4U.json
configs/com.ibm.Hardware.Chassis.Model.Rainier1S4U.json
configs/com.ibm.Hardware.Chassis.Model.Rainier2U.json
configs/com.ibm.Hardware.Chassis.Model.Rainier4U.json
configs/config_map.json

This change is due to the change of the kernel device tree
whioch has added led- to the labels of the GPIO lines used for LED
This commit also contains a config fix for missing PASS 1 hardware

Fix Rainier and Blueridge GPIO LED names

---

manager/manager.hpp
tools/clear-psu-fault-leds.hpp

This commit skips clearning the fault led of PSUs whose D-bus objects are not hosted by xyz.openbmc_project.Inventory.Manager service.
This is required in case when PLDM service hosts the PSU's of external chassis like MEX/Splitter/Nimitz, led-tool which runs on BMC should not attempt to clear it's fault led.
Test:
Tested that led-tool doesn't add a wait time to clear fault PSU leds of MEX/Splitter/Nimitz chassis.
Test log:
Feb 04 10:33:34 mexbmc systemd[1]: Starting Clears PSU fault LEDs on BMC... Feb 04 10:33:34 mexbmc obmc-clear-psu-fault-leds[1923]: Setting endpoint for object path: /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0 completed in 0 seconds. Feb 04 10:33:34 mexbmc obmc-clear-psu-fault-leds[1923]: Setting endpoint for object path: …

LED:Skip clearing external chassis's PSU fault led

---

ibm-sai.cpp
tools/clear-psu-fault-leds.hpp
tools/set-guarded-fru-leds.hpp
tools/toggle-fault-leds.hpp
tools/utility.hpp
utils.cpp
utils.hpp

During power-on, clear-all-fault-leds service clears all the fault leds by setting the functional property of the corresponding led FRU to true. While setting the property, it is calling the busctl set-property method, which updates the data only on DBus and data is not persisted.
When BMC is rebooted while host is running, on system come back, the stale data of the FRU which has functional as false will get updated on the DBus, which marks that FRU as critical on ASMI.
Changes made to use Phosphor Inventory Manager(PIM) notify method to update the functional property, which publish the data on Dbus and persist the data.

Call PIM to update the functional property

---

ibm-sai.cpp
scripts/oem/set-guarded-fru-leds.sh
scripts/oem/set-power-button-led-to-default-state.sh
utils.cpp
utils.hpp

Functional property of a FRU which is populated under the Phosphor Inventory Manager(PIM) service will have persisted value. Updating the functional property value using busctl set-property method is creating a mismatch between persisted data and the data populated on DBus, as set-property method updates the data only on the DBus. This is causing the
mismatch of the state of the FRU before and after the BMC reboot while host is running, as DBus picks the value from the stale data while host is running. 
Updated to call Notify method of PIM service which updates data on both persisted and on the DBus.

Notify PIM to update functional property

---

configs/com.ibm.Hardware.Chassis.Model.Balcones.json
configs/config_map.json

This commit has led config JSON for Balcones.
Test:
Tested on Bonnell by overwriting the bonnell json
with balcones json and verified that the below
test cases works fine.
1. BMC booted
2. Power on
3. Balcones doesn't support RDX docking station, RDX power cable port, RDX media, USB connector and power connector. Tested that the identify LED request fails on these devices on Bonnell.
busctl set-property xyz.openbmc_project.LED.GroupManager /xyz/openbmc_project/led/groups/rdx0_identify xyz.openbmc_project.Led.Group  Asserted b true Failed to set property Asserted on interface xyz.openbmc_project.Led.Group: Unknown object '/xyz/openbmc_project/led/groups/rdx0_identify'.
4. Identify request for fans/psu/cpu/connectors works as expected from GUI.
5. Identify request for system identify led …

Balcones LED config JSON
